### ISSUE TITLE
Settings reset after IDE restart

### ISSUE THREAD

**Issue by tancred423** [AlexBroadbent/timestamp-generator-plugin#11]
Everytime I choose a different format in the settings it just works as long as the IDE stays open.
Once I restart it, the settings were reset to ISO 8601 (the first option).

Anything I can do?

**Comment by PRGfx** [comment]
I tried to debug the problem and so far I'm under the impression that
- `SettingsForm::getSelectedFormat` always returns a new `TimestampFormat` (as per `TimestampFormatMap.getFormat`), so the form is always modified (i.e. `getSelectedFormat()` will never equal the current settings value)
- Once the comparison was right (e.g. when implementing `equals` on the `TimestampFormat`), a config file would be saved in the specified storage
- These settings are serialized as `<option name="format"><TimestampFormat /></option>`, so any deserialization will fail.

I guess the `TimestampGeneratorSettings` could have an internal state of `{format: string}` (and from what I gather use the `SimplePersistentStateComponent`) and implement an accessor mapping to the format enum while keeping the interface as is.
However, I neither know much about the project structure/intentions nor Kotlin in general. Maybe @AlexBroadbent has additional ideas.
